---
title: "r4bio"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{r4bio}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  message = FALSE,
  warning = FALSE
)
```

```{r setup}
library(easybio)
```


## Download and process GEO data

```{r}
# y <- download_geo('GSE119186', dir = '.')
# return a list with annotated gene expression data.table object and metadata
```

# A wrapper function for all analysis
```{r}
data(expr) # differential analysis
y <- analysis(object = expr, task = "limma", pattern = "cc", data_type = "array")
plot(y) # S3 method for all analysis
```

```{r, fig.height=10}
# GO
library(org.Hs.eg.db)
z <- analysis(object = gene_vector, task = "go")
plot(z)
```

# A R6 object for dimension reduction

```{r}
if (!requireNamespace("future")) {
  install.packages("future")
}
library(future)
library(palmerpenguins)

x <-
  penguins |>
  tidyr::drop_na()

y <- x$species
x <- x |>
  dplyr::select(where(is.numeric)) |>
  dplyr::select(-year)
x <- scale(x)
# show the results of different arguments
happy <- Reductor$new("tsne")
set.seed(20230530)
tune_fit <- happy$tune(x,
  perplexity = c(30, 40, 50, 60),
  n_iter = c(1000, 2000, 2500)
)
happy$plot(tune_fit, y)
```

